Wp=input('Normalized pass band edge: ')
Ws=input('Normalized stop band edge: ')
Rp=input('Pass band ripple: ')
Rp=10^(Rp/20)
Rs=input('Minimum stopband attenuation: ')
Rs=10^(Rs/20)
[N, Wn] = cheb1ord(Wp, Ws, Rp, Rs)
[b,a]=cheby1(N,Rp,Wn,'High')
[h,Omega]=freqz(b,a,256)
plot(Omega/pi,20*log10(abs(h)))
 